version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
